# Docker image

# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

# specific branch build
trigger:
- master

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  group: "docker hub"
  imageName: 'fable-azure-build:$(build.buildId)'
  imageNameLatest: 'fable-azure-build:latest'
  
steps:
- script: |
    echo $(dockerId)
    docker build -t $(dockerId)/$(imageName) .
  displayName: 'docker build'

#To Dockerhub
- script: docker login -u $(dockerId) -p $(dockerPassword)
  displayName: 'docker login'
  
- script: docker push $(dockerId)/$(imageName)
  displayName: 'Push image to public docker hub'

- script: docker image tag $(dockerId)/$(imageName) $(dockerId)/$(imageNameLatest)
  displayName: 'Tag image as latest for push to to public docker hub'

- script: docker push $(dockerId)/$(imageNameLatest)
  displayName: 'Push latest tag to public docker hub'

